pipeline:
  deploy:
    image: appleboy/drone-ssh
    host: serv.voixdunet.com
    command_timeout: 900
    secrets: [ssh_key]
    envs: [DRONE_COMMIT_SHA]
    script:
      - echo $DRONE_COMMIT_SHA
      - cd /home/docker/pytlas-server
      - git pull
      - docker-compose up -d --build