pipeline:
  publish:
    image: plugins/docker
    tag: latest
    registry: local-registry:5555
    repo: local-registry:5555/pytlas-server
    insecure: true
  
  deploy:
    image: appleboy/drone-ssh
    host: serv.voixdunet.com
    secrets: [ssh_key]
    script:
      - cd /home/docker/pytlas-server && docker-compose pull && docker-compose up -d