pipeline:
  deploy:
    image: appleboy/drone-ssh
    host: serv.voixdunet.com
    command_timeout: 900
    secrets: [ssh_key]
    envs: [DRONE_COMMIT_SHA]
    script:
      - cd /home/docker/pytlas-server
      - git fetch origin
      - git checkout $DRONE_COMMIT_SHA
      - docker-compose up -d --build