pipeline:
  publish:
    image: plugins/docker
    tag: latest
    repo: registry:5555/pytlas-server
    insecure: true
  
  # deploy:
  #   image: appleboy/drone-ssh
  #   host: serv.voixdunet.com
  #   command_timeout: 900
  #   secrets: [ssh_key]
  #   script:
  #     - cd /home/docker/pytlas-server
  #     - git pull
  #     - docker-compose up -d --build