version: '3'
services:
  pytlas:
    restart: unless-stopped
    build: .
    environment:
      - "WEB_DEBUG=False"
      - "WEB_ALLOWED_HOST=*"
      - "WEB_SECRET=generateAStrongSecretKeyHere"
      - "DATABASE_PATH=/data/db.sqlite"
      - "PYTLAS_LANG=fr,en"
      - "PYTLAS_SKILLS=/pytlas/skills"
      - "PYTLAS_CACHE=/pytlas/cache"
    ports:
      - 8000:8000
