# Thanks to VS code REST Client!
###

@url = http://localhost:8000
# @url = https://atlas.voixdunet.com
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNTQzODMzOTk3LCJqdGkiOiJiZjNhN2RhNjFhNzg0ODkxYjg3N2NmZTljMjE5OWE4YyIsInVzZXJfaWQiOjF9.mdwRqRGDMdAfjc2ks07GexvndQ3tEguK2ZZuGHnirKM

GET {{url}}/api
Authorization: Bearer {{token}}

###

POST {{url}}/api/token
Content-Type: application/json

{
  "username": "julien",
  "password": "forget"
}